server:
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: false
        same-site: lax
spring:
  application:
    name: RepoBoard

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github

  thymeleaf:
    cache: true

  web:
    resources:
      cache:
        period: 365d
      chain:
        strategy:
          content:
            enabled: true
            paths:
              - "/**"

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRESQL_DATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time_zone: UTC

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}

github:
  api:
    base-url: https://api.github.com
    token: ${GITHUB_API_TOKEN}

logging:
  level:
    root: INFO
    io.github.repoboard: DEBUG