spring:
  config:
    activate:
      on-profile: prod # 운영환경

  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: https://repoboard.kr/login/oauth2/code/google
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: https://repoboard.kr/login/oauth2/code/github

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: true
        same-site: lax
  shutdown: graceful
  forward-headers-strategy: native

app:
  security:
    csp: |-
      default-src 'self' https://repoboard.kr;  
      img-src 'self' https: data:;  
      style-src 'self' https://fonts.googleapis.com;  
      font-src 'self' https://fonts.gstatic.com;  
      script-src 'self' https://repoboard.kr https://apis.google.com https://accounts.google.com https://oauth2.googleapis.com https://www.googleapis.com;  
      connect-src 'self' https://repoboard.kr https://api.github.com https://apis.google.com https://accounts.google.com https://oauth2.googleapis.com https://www.googleapis.com;  
      object-src 'none';  
      base-uri 'self';  
      frame-ancestors 'self';  
      form-action 'self' https://repoboard.kr https://github.com https://accounts.google.com;
    cspReportOnly: false