spring:
  config:
    activate:
      on-profile: dev # 개발 환경

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github

  thymeleaf:
    cache: false

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: false
        same-site: lax

app:
  security:
    csp: |-
      default-src 'self' http://localhost:8080;  
      img-src 'self' https: data:;  
      style-src 'self' https://fonts.googleapis.com;  
      font-src 'self' https://fonts.gstatic.com;  
      script-src 'self' http://localhost:8080 https://apis.google.com https://accounts.google.com https://oauth2.googleapis.com https://www.googleapis.com;  
      connect-src 'self' http://localhost:8080 https://api.github.com https://apis.google.com https://accounts.google.com https://oauth2.googleapis.com https://www.googleapis.com;  
      object-src 'none';  
      base-uri 'self';  
      frame-ancestors 'self';  
      form-action 'self' http://localhost:8080 https://github.com https://accounts.google.com;
    cspReportOnly: false