spring:
  application:
    name: RepoBoard

  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRESQL_DATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time_zone: UTC

  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 30s
    scheduling:
      await-termination: true
      await-termination-period: 30s

  thymeleaf:
    cache: true

  web:
    resources:
      cache:
        period: 365d
      chain:
        strategy:
          content:
            enabled: true
            paths:
              - "/**"

logging:
  level:
    root: INFO
    io.github.repoboard: DEBUG

app:
  delete-user:
    retention-days: 7
    purge-count: "0 0 3 * * *" # 새벽 3시기준

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}

github:
  api:
    base-url: https://api.github.com
    token: ${GITHUB_API_TOKEN}
